import { getCityBySlug, CITIES } from "@/lib/db";
import { PERGOLA_TAILLES, getPergolaTailleBySlug } from "@/data/pergola-tailles";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import PergolaContentPage from "@/components/PergolaContentPage";
type Params = Promise<{ slug: string }>;
export async function generateStaticParams() { return PERGOLA_TAILLES.map((t) => ({ slug: t.slug })); }
const BASE = "https://www.expertpergolabioclimatique.fr";
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const { slug } = await params; const t = getPergolaTailleBySlug(slug); if (!t) return {}; const url = `${BASE}/tailles/${slug}`; return { title: `Pergola ${t.taille} : Prix & Installation | Expert Pergola`, description: `Pergola bioclimatique ${t.taille} (${t.dims}). ${t.prix} pose comprise. Lames orientables. Devis gratuit.`, alternates: { canonical: url }, openGraph: { title: `Pergola ${t.taille} : Prix & Devis`, description: `${t.prix}.`, locale: "fr_FR", type: "website", url, images: [{ url: t.image, width: 1200, height: 630, alt: `Pergola ${t.taille}` }] }, robots: { index: true, follow: true } }; }
export default async function TaillePage({ params }: { params: Params }) { const { slug } = await params; const t = getPergolaTailleBySlug(slug); const s = getCityBySlug("home") || Object.values(CITIES)[0]; if (!t || !s) return notFound(); const url = `${BASE}/tailles/${slug}`; const intro = `<p class="mb-4">${t.description}</p><p>Comptez entre <strong>${t.prix}</strong> pour une pergola ${t.taille} (${t.config}), fourniture et pose comprises. Devis gratuit sous 24h.</p>`; const secs = [{ title: `Configuration ${t.taille}`, html: `<ul class="space-y-2">${t.points.map((p: string) => `<li>${p}</li>`).join("")}</ul>` }, { title: `Conseil d'expert`, html: `<div class="bg-purple-50 border-l-4 border-purple-600 p-5 rounded-r-xl"><p class="text-slate-800 leading-relaxed">${t.expertTip}</p></div>` }]; return (<PergolaContentPage site={s} heroBadge="Étude de faisabilité gratuite" pageTitle={`Pergola Bioclimatique ${t.taille}`} introHtml={intro} facts={[{ label: "Dimension", value: t.dims }, { label: "Prix", value: t.prix }, { label: "Configuration", value: t.config }, { label: "Pose", value: "1-3 jours" }]} benefits={t.points} expertTip={t.expertTip} faqs={[{ question: `Quel est le prix d'une pergola ${t.taille} ?`, reponse: `Comptez entre ${t.prix} pour une pergola clé en main, fourniture et pose comprises.` }, { question: `Faut-il un permis pour une pergola ${t.taille} ?`, reponse: `Sous 20 m² d'emprise (la plupart des formats sauf 4x6 m), aucune autorisation n'est requise. Au-delà, une déclaration préalable suffit — elle est incluse dans notre service.` }]} canonicalUrl={url} heroImage={t.image} breadcrumb={[{ name: `Pergola ${t.taille}`, item: url }]} sections={secs} />); }