export const revalidate = 86400; // 24h ISR cache
import { getCityBySlug, CITIES } from "@/lib/db";
import { PERGOLA_COMPARATIFS, getPergolaComparatifBySlug } from "@/data/pergola-comparatifs";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import PergolaContentPage from "@/components/PergolaContentPage";
type Params = Promise<{ slug: string }>;
export async function generateStaticParams() { return PERGOLA_COMPARATIFS.map((c) => ({ slug: c.slug })); }
const BASE = "https://www.expertpergolabioclimatique.fr";
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const { slug } = await params; const c = getPergolaComparatifBySlug(slug); if (!c) return {}; const url = `${BASE}/comparatif/${slug}`; return { title: c.title, description: `${c.intro.slice(0, 140)} Prix indicatifs : ${c.prix}.`, alternates: { canonical: url }, openGraph: { title: c.title, description: `${c.prix}. Comparatif expert 2026.`, locale: "fr_FR", type: "website", url, images: [{ url: c.image, width: 1200, height: 630, alt: c.title }] }, robots: { index: true, follow: true } }; }
function tableHtml(c: (typeof PERGOLA_COMPARATIFS)[number]): string { const rows = c.rows.map((r) => `<tr class="border-b border-slate-200"><td class="py-3 pr-4 font-bold text-slate-900">${r.critere}</td><td class="py-3 pr-4">${r.a}</td><td class="py-3">${r.b}</td></tr>`).join(""); return `<div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b-2 border-slate-300 text-left"><th class="py-2 pr-4">Critère</th><th class="py-2 pr-4 text-purple-700">${c.a}</th><th class="py-2 text-purple-700">${c.b}</th></tr></thead><tbody>${rows}</tbody></table></div><p class="mt-4 text-xs text-slate-500">Prix indicatifs fourniture + pose.</p>`; }
export default async function ComparatifPage({ params }: { params: Params }) { const { slug } = await params; const c = getPergolaComparatifBySlug(slug); const s = getCityBySlug("home") || Object.values(CITIES)[0]; if (!c || !s) return notFound(); const url = `${BASE}/comparatif/${slug}`; const intro = `<p class="mb-4">${c.intro}</p><p>Prix indicatifs : <strong>${c.prix}</strong> fourniture et pose. Nos installateurs vous conseillent gratuitement.</p>`; const secs = [{ title: `Comparatif : ${c.a} vs ${c.b}`, html: tableHtml(c) }, { title: c.verdictTitle, html: `<div class="bg-purple-50 border-l-4 border-purple-600 p-5 rounded-r-xl"><p class="text-slate-800 leading-relaxed">${c.verdict}</p></div>` }]; return (<PergolaContentPage site={s} heroBadge="Comparatif expert 2026" pageTitle={c.title} introHtml={intro} facts={[{ label: c.a.split(" ")[0], value: "Référence" }, { label: c.b.split(" ")[0], value: "Alternative" }, { label: "Budget", value: c.prix }, { label: "Pose", value: "1-3 jours" }]} benefits={[]} expertTip="Le bon choix dépend de votre terrasse, de son exposition et de votre budget. Demandez 2 à 3 devis comparatifs à des installateurs certifiés avant de vous décider." faqs={c.faqs} canonicalUrl={url} heroImage={c.image} breadcrumb={[{ name: "Comparatifs", item: `${BASE}/comparatif` }, { name: c.title, item: url }]} sections={secs} />); }