import { getCityByCleanSlug, CITIES } from "@/lib/db";
import { PERGOLA_BRANDS, getPergolaBrandBySlug } from "@/data/pergola-brands";
import { slugify } from "@/lib/slugify";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getPseoPergolaContent } from "@/lib/pseo-pergola";
import PergolaContentPage from "@/components/PergolaContentPage";
type Params = Promise<{ slug: string; marque: string }>;
export async function generateStaticParams() { const p: { slug: string; marque: string }[] = []; Object.values(CITIES).forEach((c) => { PERGOLA_BRANDS.forEach((m) => { p.push({ slug: slugify(c.city), marque: m.slug }); }); }); return p; }
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const { slug, marque: ms } = await params; const s = getCityByCleanSlug(slug); const m = getPergolaBrandBySlug(ms); if (!s || !m) return {}; const pseo = getPseoPergolaContent(s, m); const url = `https://www.expertpergolabioclimatique.fr/ville/${slug}/${ms}`; return { title: pseo.meta_title, description: pseo.meta_description, alternates: { canonical: url }, openGraph: { title: pseo.meta_title, description: pseo.meta_description, locale: "fr_FR", type: "website", url, images: [{ url: m.image, width: 1200, height: 630, alt: `Pergola ${m.name} à ${s.city}` }] }, robots: { index: true, follow: true } }; }
export default async function CityMarquePage({ params }: { params: Params }) { const { slug, marque: ms } = await params; const site = getCityByCleanSlug(slug); const m = getPergolaBrandBySlug(ms); if (!site || !m) return notFound(); const pseo = getPseoPergolaContent(site, m); const url = `https://www.expertpergolabioclimatique.fr/ville/${slug}/${ms}`; const secs = [{ title: `Pourquoi choisir une pergola ${m.name} à ${site.city}`, html: `<ul class="space-y-2">${m.atouts.map((a: string) => `<li>${a}</li>`).join("")}</ul>` }, { title: `Limites — ${m.name}`, html: `<ul class="space-y-2">${m.limites.map((l: string) => `<li>${l}</li>`).join("")}</ul>` }, { title: `Caractéristiques`, html: `<table class="w-full text-sm"><tbody><tr><td class="py-2 pr-4 font-bold">Gamme</td><td>${m.gamme}</td></tr><tr><td class="py-2 pr-4 font-bold">Tailles</td><td>${m.tailles}</td></tr><tr><td class="py-2 pr-4 font-bold">Modèles</td><td>${m.modeles.join(", ")}</td></tr><tr><td class="py-2 pr-4 font-bold">Prix indicatif</td><td>${m.prix}</td></tr></tbody></table><p class="mt-4">Prix fourniture et pose. Devis gratuit sous 24h.</p>` }]; return (<PergolaContentPage site={site} heroBadge={`Installateur certifié ${m.name}`} pageTitle={`Pergola Bioclimatique ${m.name} à ${site.city}`} introHtml={pseo.intro_html} facts={[{ label: "Prix", value: pseo.prix }, { label: "Tailles", value: m.tailles }, { label: "Pose", value: "1-2 jours" }, { label: "Garantie", value: "10 ans" }]} benefits={pseo.atouts} expertTip={pseo.expert_tip} faqs={pseo.faqs} canonicalUrl={url} heroImage={m.image} breadcrumb={[{ name: site.city, item: `https://www.expertpergolabioclimatique.fr/ville/${slug}` }, { name: m.name, item: url }]} localHtml={pseo.soleil_html} sections={secs} />); }