export const revalidate = 86400; // 24h ISR cache
import { getCityBySlug, CITIES } from "@/lib/db";
import { PERGOLA_TYPES, getPergolaTypeBySlug } from "@/data/pergola-types";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import PergolaContentPage from "@/components/PergolaContentPage";
type Params = Promise<{ slug: string }>;
export async function generateStaticParams() { return PERGOLA_TYPES.map((t) => ({ slug: t.slug })); }
const BASE = "https://www.expertpergolabioclimatique.fr";
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const { slug } = await params; const t = getPergolaTypeBySlug(slug); if (!t) return {}; const url = `${BASE}/type/${slug}`; return { title: `${t.name} : Prix & Devis | Expert Pergola`, description: `${t.name} : ${t.prix} pose comprise. ${t.aides}. Installateurs certifiés.`, alternates: { canonical: url }, openGraph: { title: `${t.name} : Prix & Devis`, description: `${t.prix}.`, locale: "fr_FR", type: "website", url, images: [{ url: t.image, width: 1200, height: 630, alt: t.name }] }, robots: { index: true, follow: true } }; }
export default async function TypePage({ params }: { params: Params }) { const { slug } = await params; const t = getPergolaTypeBySlug(slug); const s = getCityBySlug("home") || Object.values(CITIES)[0]; if (!t || !s) return notFound(); const url = `${BASE}/type/${slug}`; const intro = `<p class="mb-4">${t.description}</p><p>Comptez entre <strong>${t.prix}</strong> pour une installation clé en main, avant déduction des aides (${t.aides}). Devis gratuit sous 24h.</p>`; const secs = [{ title: `Points clés`, html: `<ul class="space-y-2">${t.points.map((p: string) => `<li>${p}</li>`).join("")}</ul>` }, { title: `Idéal pour`, html: `<p>${t.ideal}</p>` }]; return (<PergolaContentPage site={s} heroBadge="Installateurs certifiés" pageTitle={`${t.name} : Prix & Devis`} introHtml={intro} facts={[{ label: "Prix", value: t.prix }, { label: "Durée", value: t.duree }, { label: "Aides", value: t.aides }, { label: "Idéal pour", value: t.ideal.split(",")[0] }]} benefits={t.points} expertTip={t.expertTip} faqs={[{ question: `Quel est le prix d'une ${t.shortName} ?`, reponse: `Comptez entre ${t.prix} pour une installation clé en main. Devis gratuit sous 24h.` }, { question: `Où faire installer une ${t.shortName} ?`, reponse: `Notre réseau d'installateurs certifiés intervient partout en France. Demandez votre devis gratuit.` }]} canonicalUrl={url} heroImage={t.image} breadcrumb={[{ name: t.name, item: url }]} sections={secs} />); }